[package]
name = "iot-module-template-rs"
version = "0.2.0"
edition = "2018"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>", "Jan Zachmann <jan.zachmann@conplement.de>"]
repository = "git@github.com:ICS-DeviceManagement/iot-module-template-rs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure-iot-sdk = { git = "ssh://git@github.com/ICS-DeviceManagement/azure-iot-sdk.git", branch = "main" }
serde_json = "1.0"
env_logger = "0.8"
log = "0.4"
