[package]
name = "iot-module-template-rs"
version = "0.2.1"
edition = "2018"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>", "Jan Zachmann <jan.zachmann@conplement.de>"]
repository = "git@github.com:ICS-DeviceManagement/iot-module-template-rs.git"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure-iot-sdk = { git = "ssh://git@github.com/ICS-DeviceManagement/azure-iot-sdk.git", tag = "0.4.0" }
serde_json = "1.0"
env_logger = "0.8"
log = "0.4"
