[package]
name = "iot-client-template-rs"
version = "0.3.0"
edition = "2021"
authors = ["Joerg Zeidler <joerg.zeidler@conplement.de>", "Jan Zachmann <jan.zachmann@conplement.de>"]
repository = "git@github.com:ICS-DeviceManagement/iot-client-template-rs.git"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# use either device_client, module_client or edge_client
azure-iot-sdk = { git = "ssh://git@github.com/ICS-DeviceManagement/azure-iot-sdk.git", tag = "0.8.0", default-features = false }
sd-notify = { git = "ssh://git@github.com/ICS-DeviceManagement/sd-notify.git", tag = "v0.5.0", optional = true }
serde_json = "1.0"
env_logger = "0.8"
log = "0.4"

[features]
# select if systemd ready and watchdog should be enabled
default = ["module_client", "systemd"]
systemd = ["sd-notify"]
device_client = ["azure-iot-sdk/device_client"]
module_client = ["azure-iot-sdk/module_client"]
edge_client = ["azure-iot-sdk/edge_client"]
